In [3]:
import pandas as pd

In [5]:
df=pd.read_csv('sephora_makeup.csv')
df

,url,name,brand,price,rating,reviews,image,category,product_size,shades,description,ingredients,how_to
0,https://www.sephora.sg/products/sol-de-janeiro...,Smooth And Glow Bum Bum Body Routine Set (Holi...,Sol de Janeiro,$78.00,4.8,23.0,https://image-optimizer-reg.production.sephora...,Makeup,NaN,NaN,"Formulation: Cream, Liquid, Spray | Benefits: ...","Cheirosa 62 Perfume Mist: Alcohol Denat., Aqua...",Steps for the Smooth and Glow Bum Bum Body Rou...
1,https://www.sephora.sg/products/charlotte-tilb...,Luxury Eyeshadow Palette,Charlotte Tilbury,$95.00,4.2,766.0,https://image-optimizer-reg.production.sephora...,Makeup,5.2g,"Pillow Talk, The Uptown Girl, Pillow Talk Drea...",Function: Colour | Formulation: Pressed Powder,The Uptown Girl Prime Ingredients: Calcium Sod...,Start by applying the prime shade to the entir...
2,https://www.sephora.sg/products/fenty-beauty-c...,Cheeks Suede Powder Blush,Fenty Beauty,$46.00,4.7,388.0,https://image-optimizer-reg.production.sephora...,Makeup,4g,"Brickkkk 14, Bubbleband$, Daiquiri Dip 06, Jus...","Finish: Matte, Shimmer | Formulation: Pressed ...","Petal Poppin' Ingredients: Mica, Dimethicone, ...",Gently tap your brush into the blush—a little ...
3,https://www.sephora.sg/products/rare-beauty-mi...,Mini Soft Pinch Tinted Lip Oil,Rare Beauty,$25.00,4.4,184.0,https://image-optimizer-reg.production.sephora...,Makeup,2ml,"Delight, Happy, Honesty, Hope, Wonder",Finish: High Shine | Formulation: Liquid | Ben...,"Happy Water (Aqua/Eau), Diphenyl Dimethicone, ...","How To Use: ● Swipe over bare lips, adding lay..."
4,https://www.sephora.sg/products/sephora-collec...,Color Twister Lip & Cheek Color Changing Oil-i...,Sephora Collection,$26.00,4.6,164.0,https://image-optimizer-reg.production.sephora...,Makeup,8.50g,"01 Freaky Fuschia, 02 Crazy Coral, 03 Bizarre ...","Finish: High Shine, Natural, Sheer | Formulati...",01 Freaky Fuschia Ingredients : Octyldodecanol...,What’s the best way to use the Color Twister L...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
264,https://www.sephora.sg/products/urban-decay-al...,All Nighter Ultra Glow Setting Spray,Urban Decay,$53.00,4.6,910.0,https://image-optimizer-reg.production.sephora...,Makeup,All Nighter Ultra Glow Setting Spray,"118 ML, 30 ML","Skin Type: Combination, Dry, Normal, Oily | Fi...","Aqua/Water/Eau, Alcohol Denat., Glycerin, Pvp,...",How to Use: Shake: After completing your makeu...
265,https://www.sephora.sg/products/yves-saint-lau...,Le Cushion Encre De Peau Foundation Refill,Yves Saint Laurent,$80.00,4.2,23.0,https://image-optimizer-reg.production.sephora...,Makeup,14g,"Shade 10 fair skin with neutral undertone, Sh...","Skin Type: Combination, Dry, Normal, Oily | Fi...","10,20, 25, 30, 35: Aqua / Water / Eau, Methyl ...",Insert into the refillable cushion compact. Th...
266,https://www.sephora.sg/products/charlotte-tilb...,Matte Revolution Lipstick,Charlotte Tilbury,$56.00,4.3,1844.0,https://image-optimizer-reg.production.sephora...,Makeup,3.5g,"Hollywood Vixen, Cinematic Red, Fame Flame, Fi...","Finish: Matte, Natural, Sheer | Formulation: S...","Amazing Grace, Birkin Brown, Bond Girl, Cinema...","Finished with an angled square tip, apply stra..."
267,https://www.sephora.sg/products/yves-saint-lau...,Loveshine Candy Glow,Yves Saint Laurent,$66.00,4.7,687.0,https://image-optimizer-reg.production.sephora...,Makeup,3.2g,"1B Pink Sunrise, 44B Nude Lavalliere, 3B Rosew...","Formulation: Balm | Benefits: Hydrating, Long-...","Polyglyceryl-2 Triisostearate, Bis-Behenyl/Iso...",Define your lip contours with Touche Éclat (so...
268,https://www.sephora.sg/products/rare-beauty-pe...,Perfect Strokes Longwear Gel Eyeliner,Rare Beauty,$35.00,4.4,733.0,https://image-optimizer-reg.production.sephora...,Makeup,0.25g,"Compassion, True Black, True Brown","Finish: Natural | Formulation: Cream, Gel, Pen...","True Black: Trimethylsiloxysilicate, Isododeca...",Only twist up what you need. The pencil doesn’...

In [10]:
df.shape

(269, 13)

In [11]:
df.columns.tolist()

['url',
 'name',
 'brand',
 'price',
 'rating',
 'reviews',
 'image',
 'category',
 'product_size',
 'shades',
 'description',
 'ingredients',
 'how_to']

In [8]:
df.isna().sum()

url              0
name             0
brand            0
price            0
rating          17
reviews         17
image            0
category         0
product_size     9
shades          10
description      0
ingredients      3
how_to           2
dtype: int64

In [15]:
print(df.duplicated().sum())
print(df["url"].duplicated().sum())

0
0

In [16]:
text_columns = [
    "name",
    "brand",
    "image",
    "category",
    "product_size",
    "shades",
    "description",
    "ingredients",
    "how_to"
]

for column in text_columns:
    df[column] = (
        df[column]
        .fillna("")
        .astype(str)
        .str.replace(r"\s+", " ", regex=True)
        .str.strip()
    )

In [17]:
df.head()

,url,name,brand,price,rating,reviews,image,category,product_size,shades,description,ingredients,how_to
0,https://www.sephora.sg/products/sol-de-janeiro...,Smooth And Glow Bum Bum Body Routine Set (Holi...,Sol de Janeiro,$78.00,4.8,23.0,https://image-optimizer-reg.production.sephora...,Makeup,,,"Formulation: Cream, Liquid, Spray | Benefits: ...","Cheirosa 62 Perfume Mist: Alcohol Denat., Aqua...",Steps for the Smooth and Glow Bum Bum Body Rou...
1,https://www.sephora.sg/products/charlotte-tilb...,Luxury Eyeshadow Palette,Charlotte Tilbury,$95.00,4.2,766.0,https://image-optimizer-reg.production.sephora...,Makeup,5.2g,"Pillow Talk, The Uptown Girl, Pillow Talk Drea...",Function: Colour | Formulation: Pressed Powder,The Uptown Girl Prime Ingredients: Calcium Sod...,Start by applying the prime shade to the entir...
2,https://www.sephora.sg/products/fenty-beauty-c...,Cheeks Suede Powder Blush,Fenty Beauty,$46.00,4.7,388.0,https://image-optimizer-reg.production.sephora...,Makeup,4g,"Brickkkk 14, Bubbleband$, Daiquiri Dip 06, Jus...","Finish: Matte, Shimmer | Formulation: Pressed ...","Petal Poppin' Ingredients: Mica, Dimethicone, ...",Gently tap your brush into the blush—a little ...
3,https://www.sephora.sg/products/rare-beauty-mi...,Mini Soft Pinch Tinted Lip Oil,Rare Beauty,$25.00,4.4,184.0,https://image-optimizer-reg.production.sephora...,Makeup,2ml,"Delight, Happy, Honesty, Hope, Wonder",Finish: High Shine | Formulation: Liquid | Ben...,"Happy Water (Aqua/Eau), Diphenyl Dimethicone, ...","How To Use: ● Swipe over bare lips, adding lay..."
4,https://www.sephora.sg/products/sephora-collec...,Color Twister Lip & Cheek Color Changing Oil-i...,Sephora Collection,$26.00,4.6,164.0,https://image-optimizer-reg.production.sephora...,Makeup,8.50g,"01 Freaky Fuschia, 02 Crazy Coral, 03 Bizarre ...","Finish: High Shine, Natural, Sheer | Formulati...",01 Freaky Fuschia Ingredients : Octyldodecanol...,What’s the best way to use the Color Twister L...

In [18]:
df["price"] = (
    df["price"]
    .str.replace("$", "", regex=False)
    .str.strip()
)

In [19]:
df["price"] = pd.to_numeric(
    df["price"],
    errors="coerce"
)

In [20]:
print(df["price"].dtype)
print(df["price"].head())

float64
0    78.0
1    95.0
2    46.0
3    25.0
4    26.0
Name: price, dtype: float64

In [25]:
print(df["price"].min())
print(df["price"].max())
print((df["price"] <= 0).sum())

8.0
156.0
0

In [26]:
df["rating"] = pd.to_numeric(
    df["rating"],
    errors="coerce"
)

print(df["rating"].dtype)

float64

In [27]:
print("Minimum rating:", df["rating"].min())
print("Maximum rating:", df["rating"].max())
print("Invalid ratings:", ((df["rating"] < 0) | (df["rating"] > 5)).sum())

Minimum rating: 2.0
Maximum rating: 5.0
Invalid ratings: 0

In [28]:
df.dtypes

url                 str
name                str
brand               str
price           float64
rating          float64
reviews         float64
image               str
category            str
product_size        str
shades              str
description         str
ingredients         str
how_to              str
dtype: object

In [29]:
df["reviews"] = pd.to_numeric(
    df["reviews"],
    errors="coerce"
)

print("Reviews dtype:", df["reviews"].dtype)
print("Minimum reviews:", df["reviews"].min())
print("Invalid reviews:", (df["reviews"] < 0).sum())

Reviews dtype: float64
Minimum reviews: 1.0
Invalid reviews: 0

In [30]:
print("Missing URLs:", df["url"].isnull().sum())
print("Invalid URLs:", (~df["url"].str.startswith("https://www.sephora.sg/")).sum())

Missing URLs: 0
Invalid URLs: 0

In [31]:
print("Missing categories:", df["category"].isnull().sum())
print("Unique categories:", df["category"].unique())
print("Invalid categories:", (df["category"] != "Makeup").sum())

Missing categories: 0
Unique categories: <StringArray>
['Makeup']
Length: 1, dtype: str
Invalid categories: 0

In [32]:
print("Missing product sizes:", (df["product_size"] == "").sum())
print("\nSample product sizes:")
print(df["product_size"].drop_duplicates().head(30).to_string(index=False))

Missing product sizes: 9

Sample product sizes:

                                  5.2g
                                    4g
                                   2ml
                                 8.50g
                                15.30g
                                   12g
                                  32ml
                                 29.7g
                                   15g
                                    8g
                                  30ml
                                  8.5g
       Airbrush Flawless Setting Spray
                                  3.4g
                                  7.5g
              Radiant Creamy Concealer
                                   20g
             On Til Dawn Setting Spray
                                   6ml
      Lustreglass Sheer-Shine Lipstick
                                    6g
                                   10g
                                 8.5ml
Oil Sucker Liquid Blotting Paper Spray
                                  3.5g
                                 0.5ml
                                 7.5ml
                                   9ml
             All Nighter Setting Spray

In [33]:
invalid_size_values = [
    "Airbrush Flawless Setting Spray",
    "Radiant Creamy Concealer",
    "On Til Dawn Setting Spray",
    "Lustreglass Sheer-Shine Lipstick",
    "Oil Sucker Liquid Blotting Paper Spray",
    "All Nighter Setting Spray"
]

print(df[df["product_size"].isin(invalid_size_values)][
    ["name", "product_size", "shades"]
].to_string(index=False))

                                  name                           product_size                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             shades
       Airbrush Flawless Setting Spray        Airbrush Flawless Setting Spray                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         34ml, 34 ML, 100 ML, 200ml
              Radiant Creamy Concealer               Radiant Creamy Concealer                                                                                                                                                                                                                                                                                                                                 Affogato, Cafe Au Lait, Cafe Con Leche, Cannelle, Chantilly, Crème Brulée, Creme Catalana, Custard, Ginger, Honey, Madeleine, Marron Glace, Nougatine, Macadamia, Praline, Sucre D'Orge, Toffee, Tiramisu, Vanilla
             On Til Dawn Setting Spray              On Til Dawn Setting Spray                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        46ml, 143ml
      Lustreglass Sheer-Shine Lipstick       Lustreglass Sheer-Shine Lipstick Alone Time - Greyish Mauve, Beam There, Done That - Rosy Plum Pink, Business Casual - Warm Rose Nude, Hug Me - Blushed Nude, I Deserve This - Deep Warm Brown, Lady Bug - Tomato Red, PDA - Bricky Red, Pigment Of Your Imagination - Cool Pink, Posh Pit - Warm Rose Brown Nude, See Sheer - Grapefruit Pink, Sellout - Pinky Nude With Silver Pearl, Signature Move - Burnt Orange Brown, Spice It Up - A Deep Reddish Nude, Syrup - Blue Pink, Thanks It’s MAC - Taupey Pink Nude With Silver Pearl, Well, Well, Well… - Light Pink Peachy Nude
Oil Sucker Liquid Blotting Paper Spray Oil Sucker Liquid Blotting Paper Spray                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        142ml, 45ml
             All Nighter Setting Spray              All Nighter Setting Spray                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         118 ML, 30 ML, 30ml, 118ml
              Radiant Creamy Concealer               Radiant Creamy Concealer                                                                                                                                                                                                                                                                                                                                 Affogato, Cafe Au Lait, Cafe Con Leche, Cannelle, Chantilly, Crème Brulée, Creme Catalana, Custard, Ginger, Honey, Madeleine, Marron Glace, Nougatine, Macadamia, Praline, Sucre D'Orge, Toffee, Tiramisu, Vanilla

In [34]:
# Convert empty strings back to NaN
df = df.replace("", pd.NA)

# Remove rows containing any missing value
df = df.dropna().reset_index(drop=True)

print("Dataset shape after removing null rows:", df.shape)
print("\nRemaining missing values:")
print(df.isnull().sum())

Dataset shape after removing null rows: (239, 13)

Remaining missing values:
url             0
name            0
brand           0
price           0
rating          0
reviews         0
image           0
category        0
product_size    0
shades          0
description     0
ingredients     0
how_to          0
dtype: int64

In [35]:
df.shape

(239, 13)

In [36]:
print("Duplicate rows:", df.duplicated().sum())
print("Duplicate URLs:", df["url"].duplicated().sum())

Duplicate rows: 0
Duplicate URLs: 0

In [37]:
print("Unique product sizes:", df["product_size"].nunique())

print("\nProduct sizes:")
print(df["product_size"].drop_duplicates().to_string(index=False))

Unique product sizes: 138

Product sizes:
                                            5.2g
                                              4g
                                             2ml
                                           8.50g
                                          15.30g
                                             12g
                                            32ml
                                           29.7g
                                             15g
                                              8g
                                            30ml
                                            8.5g
                 Airbrush Flawless Setting Spray
                                            3.4g
                                            7.5g
                        Radiant Creamy Concealer
                                             20g
                       On Til Dawn Setting Spray
                                             6ml
                Lustreglass Sheer-Shine Lipstick
                                              6g
                                             10g
                                           8.5ml
          Oil Sucker Liquid Blotting Paper Spray
                                            3.5g
                                           0.5ml
                                           7.5ml
                                             9ml
                       All Nighter Setting Spray
                                             3ml
                                           3.50g
                                             5ml
                                           0.08g
                                            0.3g
                                        Brow Wiz
                                           1.41g
                                           1.20g
                                            1.3g
                                            3.6g
                                           5.3ml
                                            2.2g
                         Unseen Sunscreen SPF 50
                                            10ml
                                            3.2g
                                            7.1g
                                            4.8g
                                           6.5ml
                                          3.20ml
                                             4ml
                                           0.35g
                                            3.8g
                                              5g
                    Airbrush Matte Setting Spray
                     Shape Tape™ Matte Concealer
                       Lip Contour 2.0 Lip Liner
               Express Waterproof Makeup Remover
                                            2.8g
                                            37ml
                                             29g
         Easy Blur Silicon-Free Smoothing Primer
                                              1g
                    BADgal Bang! Mascara - Black
                    Airbrush Flawless Foundation
                                            55ml
                                            1.2g
                          New Clear Eyelash Glue
                                              7g
                        Micellar Cleansing Water
                                            0.2g
                                             1ml
                                 Brow Freeze Gel
                                            11ml
                                            0.7g
                 Take The Day Off Cleansing Balm
                                           4.5ml
    Fix+ Alcohol-Free Multitasking Setting Spray
                                            1.9g
                                              3g
                                            1.7g
                                             11g
                                           4.50g
                                             7ml
            Veil Translucent Setting Powder Mini
    Perfect Strokes Universal Volumizing Mascara
                   Tartelette™ XL Tubing Mascara
                            Makeup Setting Spray
                                            2.7g
                                             18g
                                            1.4g
                         Secure the Sweat Primer
                                            4.5g
                   The POREfessional Face Primer
                                           0.34g
                                           8.30g
                                            1.5g
                                           1.3ml
                              Soft Arch Brow Kit
                                              2g
                                  Glossy Lip Kit
                                            4.4g
                                            2.5g
                                            25ml
              It's A Stretch Mascara Ultra Black
                                            0.4g
                                  Dipbrow Pomade
            24-Hr Brow Setter Invisible Brow Gel
                                           0.06g
                                  Fix+ Stay Over
                                             1pc
                                           2.8ml
                                            9.3g
                                             19g
                                           1.50g
              Colored Clay CC Undereye Corrector
                      Hydrate & Glow Face Primer
                                           0.04g
                       Benetint Cheek & Lip Tint
                                           10.5g
                                            4.2g
                                              9g
            Light Reflecting Setting Powder Mini
                                8.5g - Universal
                      All That Matte(r)s Palette
                                           5.50g
The Original Photo Finish Smooth And Blur Primer
         You Mist Makeup-Extending Setting Spray
                                           1.24g
                                            0.1g
          Grip Trip Mattifying + Blurring Primer
                                            1.8g
                  Mist & Fix Matte Setting Spray
                                            6.7g
                                            1.1g
                       Glow Makeup Setting Spray
                                          3.90ml
            All Nighter Ultra Glow Setting Spray
                                             14g
                                           0.25g

In [38]:
import re

size_pattern = r"^\s*\d+(\.\d+)?\s*(g|kg|ml|l|oz|pcs?|pc)\s*(?:-\s*.+)?\s*$"

invalid_sizes = ~df["product_size"].str.match(
    size_pattern,
    case=False,
    na=False
)

print("Invalid product_size values:", invalid_sizes.sum())
print("Total rows:", len(df))

Invalid product_size values: 44
Total rows: 239

In [39]:
print(
    df.loc[invalid_sizes, ["name", "product_size", "shades"]]
    .to_string(index=False)
)

                                            name                                     product_size                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             shades
                 Airbrush Flawless Setting Spray                  Airbrush Flawless Setting Spray                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         34ml, 34 ML, 100 ML, 200ml
                        Radiant Creamy Concealer                         Radiant Creamy Concealer                                                                                                                                                                                                                                                                                                                                 Affogato, Cafe Au Lait, Cafe Con Leche, Cannelle, Chantilly, Crème Brulée, Creme Catalana, Custard, Ginger, Honey, Madeleine, Marron Glace, Nougatine, Macadamia, Praline, Sucre D'Orge, Toffee, Tiramisu, Vanilla
                       On Til Dawn Setting Spray                        On Til Dawn Setting Spray                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        46ml, 143ml
                Lustreglass Sheer-Shine Lipstick                 Lustreglass Sheer-Shine Lipstick Alone Time - Greyish Mauve, Beam There, Done That - Rosy Plum Pink, Business Casual - Warm Rose Nude, Hug Me - Blushed Nude, I Deserve This - Deep Warm Brown, Lady Bug - Tomato Red, PDA - Bricky Red, Pigment Of Your Imagination - Cool Pink, Posh Pit - Warm Rose Brown Nude, See Sheer - Grapefruit Pink, Sellout - Pinky Nude With Silver Pearl, Signature Move - Burnt Orange Brown, Spice It Up - A Deep Reddish Nude, Syrup - Blue Pink, Thanks It’s MAC - Taupey Pink Nude With Silver Pearl, Well, Well, Well… - Light Pink Peachy Nude
          Oil Sucker Liquid Blotting Paper Spray           Oil Sucker Liquid Blotting Paper Spray                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        142ml, 45ml
                       All Nighter Setting Spray                        All Nighter Setting Spray                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         118 ML, 30 ML, 30ml, 118ml
                                        Brow Wiz                                         Brow Wiz                                                                                                                                                                                                                                                                                                                                                                                                                              Blonde, Medium Brown, Taupe, Caramel, Auburn, Soft Brown, Chocolate, Dark Brown, Ebony, Granite, Ash Brown, Strawburn
                         Unseen Sunscreen SPF 50                          Unseen Sunscreen SPF 50                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         50ml, 20ml
                    Airbrush Matte Setting Spray                     Airbrush Matte Setting Spray                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        100ml, 34ml
                     Shape Tape™ Matte Concealer                      Shape Tape™ Matte Concealer                                      8B porcelain beige, 12B Fair Beige, 12N Fair Neutral, 12S Fair, 16N fair-light neutral, 20B Light, 20S Light Sand, 22N Light Neutral, 22B light beige, 27H Light-medium Honey, 27S Light-medium Sand, 27B light-medium beige, 29N Light Medium, 34S medium sand, 35H Medium Honey, 35N Medium, 36S Medium-tan Sand, 37G medium-tan golden, 38N medium-tan neutral, 42S Tan Sand, 44H Tan, 47H tan-deep honey, 47S Tan-deep Sand, 53N Deep, 53S deep sand, 57N Rich, 57S rich sand, 60N Mahogany, 61H Espresso
                       Lip Contour 2.0 Lip Liner                        Lip Contour 2.0 Lip Liner                                                                                                                                                                                                                                                                                                                                                                                                                                        Rusty Pink, Very Berry, Deep Rose, Rich Brown, Muted Pink, Honey Beige, Terracotta, Warm Brown, Pinky Brown
               Express Waterproof Makeup Remover                Express Waterproof Makeup Remover                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        200ml, 50ml
                        Radiant Creamy Concealer                         Radiant Creamy Concealer                                                                                                                                                                                                                                                                                                                                 Affogato, Cafe Au Lait, Cafe Con Leche, Cannelle, Chantilly, Crème Brulée, Creme Catalana, Custard, Ginger, Honey, Madeleine, Marron Glace, Nougatine, Macadamia, Praline, Sucre D'Orge, Toffee, Tiramisu, Vanilla
         Easy Blur Silicon-Free Smoothing Primer          Easy Blur Silicon-Free Smoothing Primer                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         10ml, 30ml
                    BADgal Bang! Mascara - Black                     BADgal Bang! Mascara - Black                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           8.5g, 4g
                    Airbrush Flawless Foundation                     Airbrush Flawless Foundation                                                                                                                                                                                                                                                                                                              1 Neutral, 1 Cool, 2 Cool, 2 Warm, 2 Neutral, 3 Cool, 3 Neutral, 3 Warm, 4 Cool, 4 Neutral, 4 Warm, 5 Cool, 5 Neutral, 5 Warm, 6 Cool, 6 Neutral, 6 Warm, 7 Neutral, 7 Warm, 8 Neutral, 9 Neutral, 10 Neutral, 11 Neutral, 12 Neutral
                          New Clear Eyelash Glue                           New Clear Eyelash Glue                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              3.5ml
                        Micellar Cleansing Water                         Micellar Cleansing Water                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 400ml, 200ml, 50ml
                                 Brow Freeze Gel                                  Brow Freeze Gel                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         7ml, 4.5ml
                 Take The Day Off Cleansing Balm                  Take The Day Off Cleansing Balm                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        125ml, 30ml
    Fix+ Alcohol-Free Multitasking Setting Spray     Fix+ Alcohol-Free Multitasking Setting Spray                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               30ml
            Veil Translucent Setting Powder Mini             Veil Translucent Setting Powder Mini                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 2g
    Perfect Strokes Universal Volumizing Mascara     Perfect Strokes Universal Volumizing Mascara                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        13.5ml, 8ml
                   Tartelette™ XL Tubing Mascara                    Tartelette™ XL Tubing Mascara                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           8ml, 4ml
                            Makeup Setting Spray                             Makeup Setting Spray                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         80ml, 40ml
                         Secure the Sweat Primer                          Secure the Sweat Primer                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         30ml, 10ml
                   The POREfessional Face Primer                    The POREfessional Face Primer                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  44ml, 22ml, 7.5ml
                              Soft Arch Brow Kit                               Soft Arch Brow Kit                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               Dark Brown, Medium Brown, Soft Brown
                                  Glossy Lip Kit                                   Glossy Lip Kit                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     Candy Pink, Coconut, Comes Naturally, Dolce K, Espresso, Kylie
              It's A Stretch Mascara Ultra Black               It's A Stretch Mascara Ultra Black                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           8ml, 5ml

In [40]:
size_from_shades = df["shades"].str.findall(
    r"\b\d+(?:\.\d+)?\s*(?:g|kg|ml|l|oz|pcs?|pc)\b",
    flags=re.IGNORECASE
)

mask = invalid_sizes & size_from_shades.str.len().gt(0)

df.loc[mask, "product_size"] = size_from_shades[mask].apply(
    lambda x: ", ".join(dict.fromkeys(x))
)

print("Product sizes fixed:", mask.sum())

Product sizes fixed: 33

In [41]:
print(
    df.loc[invalid_sizes, ["name", "product_size", "shades"]]
    .to_string(index=False)
)

                                            name                       product_size                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             shades
                 Airbrush Flawless Setting Spray         34ml, 34 ML, 100 ML, 200ml                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         34ml, 34 ML, 100 ML, 200ml
                        Radiant Creamy Concealer           Radiant Creamy Concealer                                                                                                                                                                                                                                                                                                                                 Affogato, Cafe Au Lait, Cafe Con Leche, Cannelle, Chantilly, Crème Brulée, Creme Catalana, Custard, Ginger, Honey, Madeleine, Marron Glace, Nougatine, Macadamia, Praline, Sucre D'Orge, Toffee, Tiramisu, Vanilla
                       On Til Dawn Setting Spray                        46ml, 143ml                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        46ml, 143ml
                Lustreglass Sheer-Shine Lipstick   Lustreglass Sheer-Shine Lipstick Alone Time - Greyish Mauve, Beam There, Done That - Rosy Plum Pink, Business Casual - Warm Rose Nude, Hug Me - Blushed Nude, I Deserve This - Deep Warm Brown, Lady Bug - Tomato Red, PDA - Bricky Red, Pigment Of Your Imagination - Cool Pink, Posh Pit - Warm Rose Brown Nude, See Sheer - Grapefruit Pink, Sellout - Pinky Nude With Silver Pearl, Signature Move - Burnt Orange Brown, Spice It Up - A Deep Reddish Nude, Syrup - Blue Pink, Thanks It’s MAC - Taupey Pink Nude With Silver Pearl, Well, Well, Well… - Light Pink Peachy Nude
          Oil Sucker Liquid Blotting Paper Spray                        142ml, 45ml                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        142ml, 45ml
                       All Nighter Setting Spray         118 ML, 30 ML, 30ml, 118ml                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         118 ML, 30 ML, 30ml, 118ml
                                        Brow Wiz                           Brow Wiz                                                                                                                                                                                                                                                                                                                                                                                                                              Blonde, Medium Brown, Taupe, Caramel, Auburn, Soft Brown, Chocolate, Dark Brown, Ebony, Granite, Ash Brown, Strawburn
                         Unseen Sunscreen SPF 50                         50ml, 20ml                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         50ml, 20ml
                    Airbrush Matte Setting Spray                        100ml, 34ml                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        100ml, 34ml
                     Shape Tape™ Matte Concealer                                37G                                      8B porcelain beige, 12B Fair Beige, 12N Fair Neutral, 12S Fair, 16N fair-light neutral, 20B Light, 20S Light Sand, 22N Light Neutral, 22B light beige, 27H Light-medium Honey, 27S Light-medium Sand, 27B light-medium beige, 29N Light Medium, 34S medium sand, 35H Medium Honey, 35N Medium, 36S Medium-tan Sand, 37G medium-tan golden, 38N medium-tan neutral, 42S Tan Sand, 44H Tan, 47H tan-deep honey, 47S Tan-deep Sand, 53N Deep, 53S deep sand, 57N Rich, 57S rich sand, 60N Mahogany, 61H Espresso
                       Lip Contour 2.0 Lip Liner          Lip Contour 2.0 Lip Liner                                                                                                                                                                                                                                                                                                                                                                                                                                        Rusty Pink, Very Berry, Deep Rose, Rich Brown, Muted Pink, Honey Beige, Terracotta, Warm Brown, Pinky Brown
               Express Waterproof Makeup Remover                        200ml, 50ml                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        200ml, 50ml
                        Radiant Creamy Concealer           Radiant Creamy Concealer                                                                                                                                                                                                                                                                                                                                 Affogato, Cafe Au Lait, Cafe Con Leche, Cannelle, Chantilly, Crème Brulée, Creme Catalana, Custard, Ginger, Honey, Madeleine, Marron Glace, Nougatine, Macadamia, Praline, Sucre D'Orge, Toffee, Tiramisu, Vanilla
         Easy Blur Silicon-Free Smoothing Primer                         10ml, 30ml                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         10ml, 30ml
                    BADgal Bang! Mascara - Black                           8.5g, 4g                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           8.5g, 4g
                    Airbrush Flawless Foundation       Airbrush Flawless Foundation                                                                                                                                                                                                                                                                                                              1 Neutral, 1 Cool, 2 Cool, 2 Warm, 2 Neutral, 3 Cool, 3 Neutral, 3 Warm, 4 Cool, 4 Neutral, 4 Warm, 5 Cool, 5 Neutral, 5 Warm, 6 Cool, 6 Neutral, 6 Warm, 7 Neutral, 7 Warm, 8 Neutral, 9 Neutral, 10 Neutral, 11 Neutral, 12 Neutral
                          New Clear Eyelash Glue                              3.5ml                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              3.5ml
                        Micellar Cleansing Water                 400ml, 200ml, 50ml                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 400ml, 200ml, 50ml
                                 Brow Freeze Gel                         7ml, 4.5ml                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         7ml, 4.5ml
                 Take The Day Off Cleansing Balm                        125ml, 30ml                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        125ml, 30ml
    Fix+ Alcohol-Free Multitasking Setting Spray                               30ml                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               30ml
            Veil Translucent Setting Powder Mini                                 2g                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 2g
    Perfect Strokes Universal Volumizing Mascara                        13.5ml, 8ml                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        13.5ml, 8ml
                   Tartelette™ XL Tubing Mascara                           8ml, 4ml                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           8ml, 4ml
                            Makeup Setting Spray                         80ml, 40ml                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         80ml, 40ml
                         Secure the Sweat Primer                         30ml, 10ml                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         30ml, 10ml
                   The POREfessional Face Primer                  44ml, 22ml, 7.5ml                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  44ml, 22ml, 7.5ml
                              Soft Arch Brow Kit                 Soft Arch Brow Kit                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               Dark Brown, Medium Brown, Soft Brown
                                  Glossy Lip Kit                     Glossy Lip Kit                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     Candy Pink, Coconut, Comes Naturally, Dolce K, Espresso, Kylie
              It's A Stretch Mascara Ultra Black                           8ml, 5ml                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           8ml, 5ml
                                  Dipbrow Pomade                     Dipbrow Pomade                                                                                                                                                                                                                                                                                                                                                                                                                                         Blonde, Taupe, Soft Brown, Medium Brown, Caramel, Auburn, Chocolate, Dark Brown, Ebony, Ash Brown, Granite

In [42]:
invalid_sizes = ~df["product_size"].str.match(
    size_pattern,
    case=False,
    na=False
)

print("Remaining invalid product_size values:", invalid_sizes.sum())

Remaining invalid product_size values: 38

In [43]:
df.loc[invalid_sizes, "product_size"] = pd.NA

print("Invalid product_size values remaining:",
      (~df["product_size"].str.match(
          size_pattern,
          case=False,
          na=False
      )).sum())

print("Missing product_size values:",
      df["product_size"].isna().sum())

Invalid product_size values remaining: 38
Missing product_size values: 38

In [44]:
invalid_sizes = (
    df["product_size"].notna()
    & ~df["product_size"].str.match(
        size_pattern,
        case=False,
        na=False
    )
)

print("Invalid product_size values:", invalid_sizes.sum())
print("Missing product_size values:", df["product_size"].isna().sum())

Invalid product_size values: 0
Missing product_size values: 38

In [45]:
print("Missing shades:", df["shades"].isna().sum())
print("Unique shades:", df["shades"].nunique())

print("\nSample shades:")
print(df["shades"].drop_duplicates().head(20).to_string(index=False))

Missing shades: 0
Unique shades: 233

Sample shades:
Pillow Talk, The Uptown Girl, Pillow Talk Dream...
Brickkkk 14, Bubbleband$, Daiquiri Dip 06, Just...
             Delight, Happy, Honesty, Hope, Wonder
01 Freaky Fuschia, 02 Crazy Coral, 03 Bizarre B...
                                          Tempting
C3.5​ - Light To Medium Beige With Peachy Under...
100 - Light with neutral undertones, 110 - Ligh...
1C Ready, 2N Pep, 3W Fun, 4C Charm, 5N Go, 6W L...
Brightening Peach, Brightening Pink, Translucen...
Blushgasm, Ecstasy, Forbidden Cherry, Loved Up,...
Light 106N, Light 116C, Light 136N, Light 126N,...
01 Crystal, 206 Dreamy Pink, 312 Soft Coral, 42...
Banana Bread, Cherry Blossom Cake, Cinnamon Bun...
1 Rose Blush, 2 Caramel Blush, 3 Apricot Blush,...
                        34ml, 34 ML, 100 ML, 200ml
Bloom, Dream, Embrace, Fortune, Journey, Muse, ...
04P - Light, 06Y- Light, 08N - Light, 12N - Lig...
Affogato, Cafe Au Lait, Cafe Con Leche, Cannell...
Cherry Blossom Cake, Cupcake, Banana Bread, Blo...
                                       46ml, 143ml

In [46]:
shade_size_pattern = r"^\s*\d+(?:\.\d+)?\s*(?:g|kg|ml|l|oz|pcs?|pc)(?:\s*,\s*\d+(?:\.\d+)?\s*(?:g|kg|ml|l|oz|pcs?|pc))*\s*$"

invalid_shades = (
    ~df["shades"].str.match(
        shade_size_pattern,
        case=False,
        na=False
    )
)

print("Values containing only sizes:", (~invalid_shades).sum())
print("Values that are not only sizes:", invalid_shades.sum())

Values containing only sizes: 33
Values that are not only sizes: 206

In [47]:
size_only_mask = df["shades"].str.match(
    shade_size_pattern,
    case=False,
    na=False
)

df.loc[size_only_mask, "shades"] = pd.NA

print("Size-only shades removed:", size_only_mask.sum())
print("Missing shades after cleaning:", df["shades"].isna().sum())

Size-only shades removed: 33
Missing shades after cleaning: 33

In [48]:
print("Missing descriptions:", df["description"].isna().sum())
print("Empty descriptions:", (df["description"].str.strip() == "").sum())

print("\nSample descriptions:")
print(df["description"].head(5).to_string(index=False))

Missing descriptions: 0
Empty descriptions: 0

Sample descriptions:
    Function: Colour | Formulation: Pressed Powder
Finish: Matte, Shimmer | Formulation: Pressed P...
Finish: High Shine | Formulation: Liquid | Bene...
Finish: High Shine, Natural, Sheer | Formulatio...
Function: Colour | Finish: Glitter, Matte, Sati...

In [49]:
print("Missing ingredients:", df["ingredients"].isna().sum())
print("Empty ingredients:", (df["ingredients"].str.strip() == "").sum())

print("\nSample ingredients:")
print(df["ingredients"].head(5).to_string(index=False))

Missing ingredients: 0
Empty ingredients: 0

Sample ingredients:
The Uptown Girl Prime Ingredients: Calcium Sodi...
Petal Poppin' Ingredients: Mica, Dimethicone, T...
Happy Water (Aqua/Eau), Diphenyl Dimethicone, D...
01 Freaky Fuschia Ingredients : Octyldodecanol,...
Love Me Not: Ingredients: Dimethicone, Syntheti...

In [50]:
print("Missing how_to:", df["how_to"].isna().sum())
print("Empty how_to:", (df["how_to"].str.strip() == "").sum())

print("\nSample how_to:")
print(df["how_to"].head(5).to_string(index=False))

Missing how_to: 0
Empty how_to: 0

Sample how_to:
Start by applying the prime shade to the entire...
Gently tap your brush into the blush—a little g...
How To Use: ● Swipe over bare lips, adding laye...
What’s the best way to use the Color Twister Li...
Build a base of color for shimmer shades to pop...

In [51]:
print("========== FINAL VALIDATION ==========")

print("Shape:", df.shape)

print("\nMissing values:")
print(df.isnull().sum())

print("\nDuplicate rows:", df.duplicated().sum())
print("Duplicate URLs:", df["url"].duplicated().sum())

print("\nPrice range:")
print("Min:", df["price"].min())
print("Max:", df["price"].max())

print("\nRating range:")
print("Min:", df["rating"].min())
print("Max:", df["rating"].max())

print("\nReviews:")
print("Min:", df["reviews"].min())
print("Negative reviews:", (df["reviews"] < 0).sum())

print("\nCategories:")
print(df["category"].value_counts())

========== FINAL VALIDATION ==========
Shape: (239, 13)

Missing values:
url              0
name             0
brand            0
price            0
rating           0
reviews          0
image            0
category         0
product_size    38
shades          33
description      0
ingredients      0
how_to           0
dtype: int64

Duplicate rows: 0
Duplicate URLs: 0

Price range:
Min: 11.0
Max: 122.0

Rating range:
Min: 2.0
Max: 5.0

Reviews:
Min: 1.0
Negative reviews: 0

Categories:
category
Makeup    239
Name: count, dtype: int64

In [52]:
# Remove rows with missing product_size OR shades
df = df.dropna(
    subset=["product_size", "shades"]
).reset_index(drop=True)

print("Final shape:", df.shape)
print("\nMissing values:")
print(df[["product_size", "shades"]].isnull().sum())

Final shape: (194, 13)

Missing values:
product_size    0
shades          0
dtype: int64

In [53]:
print("========== FINAL DATASET ==========")
print("Shape:", df.shape)

print("\nMissing values:")
print(df.isnull().sum())

print("\nDuplicate rows:", df.duplicated().sum())
print("Duplicate URLs:", df["url"].duplicated().sum())

========== FINAL DATASET ==========
Shape: (194, 13)

Missing values:
url             0
name            0
brand           0
price           0
rating          0
reviews         0
image           0
category        0
product_size    0
shades          0
description     0
ingredients     0
how_to          0
dtype: int64

Duplicate rows: 0
Duplicate URLs: 0

In [54]:
df.to_csv(
    "sephora_makeup_cleaned.csv",
    index=False,
    encoding="utf-8-sig"
)

print("\nSaved: sephora_makeup_cleaned.csv")
print("Final shape:", df.shape)

Saved: sephora_makeup_cleaned.csv
Final shape: (194, 13)