In [19]:
import pandas as pd
df=pd.read_csv('bayut_properties.csv')
df

,url,reference_number,id,broker_display_name,title,property_type,description,location,price,currency,bedrooms,bathrooms,furnished,amenities,details,agent_name,property_image_urls,completion_status,ownership
0,https://www.bayut.eg/en/property/details-50397...,Bayut - 042015,503976030,Remax Avalon,Apartment for sale 165 m Smouha (Sh Adamon Fre...,Apartment,"شقة للبيع 165 م سموحه ( ش ادمون فريمون ) - 5,0...","Smoha, Alexandria","5,000,000",EGP,4,1.0,Unfurnished,NaN,165 Sq. M.,Aly Sallam,"[""https://images.bayut.eg/thumbnails/48290666-...",Ready,Resale
1,https://www.bayut.eg/en/property/details-50403...,Bayut - 1412-oZqhry,504034847,Property Hills One 1,"A villa overlooking a landscaped area, ready f...",Villa,A fully finished villa with an ultra-superb fi...,"Sodic East, New Heliopolis, Cairo","33,000,000",EGP,4,4.0,Furnished,"Built in Kitchen Appliances, Furnished, Covere...",331 Sq. M.,Santi Tareq,"[""https://images.bayut.eg/thumbnails/49130472-...",Ready,Primary
2,https://www.bayut.eg/en/property/details-50403...,Bayut - 1412-KXhp1U,504034783,Property Hills One 1,The last villa in the compound is ready for vi...,Villa,The last villa in the compound is ready for vi...,"Ivy Residence, Shorouk City, Cairo","15,000,000",EGP,5,5.0,Unfurnished,NaN,376 Sq. M.,merna elkady,"[""https://images.bayut.eg/thumbnails/49130137-...",Ready,Primary
3,https://www.bayut.eg/en/property/details-50403...,Bayut - 1016-lNhXuj,504034767,Falcon Real Estate,Townhouse with view of Central Park in La Vist...,Townhouse,with 25% cash discount prime Townhouse with op...,"Patio Town Compound, 5th Settlement, New Cairo...","22,500,000",EGP,4,4.0,NaN,NaN,223 Sq. M.,abdelrahman mohamed elsaidy,"[""https://images.bayut.eg/thumbnails/49129847-...",Ready,Primary
4,https://www.bayut.eg/en/property/details-50403...,Bayut - 1016-uZZby7,504034491,Falcon Real Estate,Duplex 206m + Garden Open View Opposite Madina...,Apartment,206m² Private Garden Duplex | Prime Madinaty V...,"Sarai, Mostakbal City, Cairo","8,200,000",EGP,4,4.0,Unfurnished,"Gym or Health Club, Swimming Pool, Jacuzzi, Sa...",206 Sq. M.,Dina Mohamed,"[""https://images.bayut.eg/thumbnails/49126818-...",Off-Plan,Primary
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
444,https://www.bayut.eg/en/property/details-50366...,Bayut - 6206-qW9tr6,503666619,AL Hayah Investment,10% down payment for an independent villa of 2...,Villa,An opportunity for contracting with a low down...,"Sukoon, New Zayed, Sheikh Zayed, Giza Villas, ...","14,000,000",EGP,3,3.0,Unfurnished,"Covered parking, Pets Allowed, Electricity Met...",285 Sq. M.,Nour Ashraf,"[""https://images.bayut.eg/thumbnails/44340174-...",Off-Plan,Primary
445,https://www.bayut.eg/en/property/details-50401...,Bayut - 8068-81bYxm,504017827,AL Essamy Group,"Apartment of 141 m for sale in Madinaty B14, r...",Apartment,With the first deliveries of B14 for sale at t...,"Madinaty, Cairo","9,400,000",EGP,3,2.0,Unfurnished,"Electricity Meter, Water Meter, Natural Gas, L...",141 Sq. M.,Ahmed Mostafa,"[""https://images.bayut.eg/thumbnails/48901454-...",Off-Plan,Primary
446,https://www.bayut.eg/en/property/details-50401...,Bayut - 3XZ66J0JS6BHDRRCCX4EVY0DB8.N,504018932,KPIS real estate,Own a Chalet with a Large Private Garden | Sea...,Chalet,location : M Square Chalet - Ras El Hekma_- Ar...,"Ras Al Hekma, North Coast, Matruh Chalets, Matruh","19,000,000",EGP,3,3.0,Unfurnished,NaN,175 Sq. M.,Mohab Abdel Wahed,"[""https://images.bayut.eg/thumbnails/48952186-...",Off-Plan,Primary
447,https://www.bayut.eg/en/property/details-50402...,Bayut - calicoast3,504020641,GRAVITY,Own a beachfront chalet with a 35% discount an...,Chalet,Your chance to live by the sea on the North Co...,"Cali Coast, Ras Al Hekma, North Coast, Matruh ...","9,985,000",EGP,2,1.0,Unfurnished,"Built in Kitchen Appliances, Furnished, Covere...",86 Sq. M.,passant tarek,"[""https://images.bayut.eg/thumbnails/48931926-...",Off-Plan,Primary
448,https://www.bayut.eg/en/property/details-50374...,Bayut - 6206-OgnJyf,503745630,AL Hayah Investment,"At the lowest price you can find, own a Sky Vi...",Villa,A once-in-a-lifetime opportunity. Own a Sky Vi...,"LA Joie Havre, New Zayed, Sheikh Zayed, Giza V...","5,775,000",EGP,3,3.0,Unfurnished,"Gym or Health Club, Swimming Pool, Kids Play A...",160 Sq. M.,esraa ahmed,"[""https://images.bayut.eg/thumbnails/45279865-...",Off-Plan,Primary

In [20]:
df.shape

(449, 19)

In [21]:
df.isna().sum()

url                      0
reference_number         0
id                       0
broker_display_name      0
title                    0
property_type            0
description              0
location                 0
price                    0
currency                 0
bedrooms                 0
bathrooms                1
furnished               62
amenities              194
details                  0
agent_name               0
property_image_urls      0
completion_status        0
ownership                2
dtype: int64

In [22]:
df=df.dropna(subset=['bathrooms','furnished','amenities','ownership'])

In [23]:
df.isna().sum()

url                    0
reference_number       0
id                     0
broker_display_name    0
title                  0
property_type          0
description            0
location               0
price                  0
currency               0
bedrooms               0
bathrooms              0
furnished              0
amenities              0
details                0
agent_name             0
property_image_urls    0
completion_status      0
ownership              0
dtype: int64

In [24]:
df.shape

(221, 19)

In [25]:
print(f"Duplicate Values: {df.duplicated().sum()}")

Duplicate Values: 0

In [26]:
df.dtypes

url                        str
reference_number           str
id                       int64
broker_display_name        str
title                      str
property_type              str
description                str
location                   str
price                      str
currency                   str
bedrooms                 int64
bathrooms              float64
furnished                  str
amenities                  str
details                    str
agent_name                 str
property_image_urls        str
completion_status          str
ownership                  str
dtype: object

In [27]:
c=['property_type','completion_status','ownership','furnished']
for i in c:
    print(df[i].value_counts())
    print(100*'*')

property_type
Apartment     92
Villa         60
Chalet        43
Townhouse     12
Twin House     7
Duplex         5
Penthouse      2
Name: count, dtype: int64
****************************************************************************************************
completion_status
Off-Plan    136
Ready        85
Name: count, dtype: int64
****************************************************************************************************
ownership
Primary    192
Resale      29
Name: count, dtype: int64
****************************************************************************************************
furnished
Unfurnished    198
Furnished       23
Name: count, dtype: int64
****************************************************************************************************

In [28]:
df['price']

1      33,000,000
4       8,200,000
6      20,000,000
15     10,497,000
27      3,600,000
          ...
443     5,250,000
444    14,000,000
445     9,400,000
447     9,985,000
448     5,775,000
Name: price, Length: 221, dtype: str

In [29]:
df['price'] = df['price'].str.replace(',','')
df['price'] = pd.to_numeric(df['price'])
df['price']

1      33000000
4       8200000
6      20000000
15     10497000
27      3600000
         ...
443     5250000
444    14000000
445     9400000
447     9985000
448     5775000
Name: price, Length: 221, dtype: int64

In [30]:
df.dtypes

url                        str
reference_number           str
id                       int64
broker_display_name        str
title                      str
property_type              str
description                str
location                   str
price                    int64
currency                   str
bedrooms                 int64
bathrooms              float64
furnished                  str
amenities                  str
details                    str
agent_name                 str
property_image_urls        str
completion_status          str
ownership                  str
dtype: object

In [31]:
print("Rows:", len(df))
print("Columns:", len(df.columns))
print("Null values:", df.isna().sum().sum())
print("Duplicate rows:", df.duplicated().sum())

Rows: 221
Columns: 19
Null values: 0
Duplicate rows: 0

In [32]:
ind=['url', 'reference_number', 'id', 'broker_display_name', 'title',
       'property_type', 'description', 'location', 'price', 'currency',
       'bedrooms', 'bathrooms', 'furnished', 'amenities', 'details',
       'agent_name', 'property_image_urls', 'completion_status', 'ownership']

for i in ind:
    print(df[i].head(5))
    print(100*'*')

1     https://www.bayut.eg/en/property/details-50403...
4     https://www.bayut.eg/en/property/details-50403...
6     https://www.bayut.eg/en/property/details-50403...
15    https://www.bayut.eg/en/property/details-50403...
27    https://www.bayut.eg/en/property/details-50403...
Name: url, dtype: str
****************************************************************************************************
1     Bayut - 1412-oZqhry
4     Bayut - 1016-uZZby7
6     Bayut - 1016-kb5nH9
15    Bayut - 1016-Z08cJv
27    Bayut - 1016-4dp8xi
Name: reference_number, dtype: str
****************************************************************************************************
1     504034847
4     504034491
6     504034500
15    504034685
27    504034450
Name: id, dtype: int64
****************************************************************************************************
1     Property Hills One 1
4       Falcon Real Estate
6       Falcon Real Estate
15      Falcon Real Estate
27      Falcon Real Estate
Name: broker_display_name, dtype: str
****************************************************************************************************
1     A villa overlooking a landscaped area, ready f...
4     Duplex 206m + Garden Open View Opposite Madina...
6     1st Row Lagoon Twin Chalet + Garden 60s to Sea...
15    Villa view landscape & water feature 50% disco...
27    Ultra Lux Apartment 33% Off + 10Y Plan Next to...
Name: title, dtype: str
****************************************************************************************************
1         Villa
4     Apartment
6        Chalet
15        Villa
27    Apartment
Name: property_type, dtype: str
****************************************************************************************************
1     A fully finished villa with an ultra-superb fi...
4     206m² Private Garden Duplex | Prime Madinaty V...
6     Invest with Diar Qatar in Alam Al Roum’s MEGA ...
15    Prime villa available on system in Taj City Co...
27    Apartment with a breathtaking Landscape View i...
Name: description, dtype: str
****************************************************************************************************
1                     Sodic East, New Heliopolis, Cairo
4                          Sarai, Mostakbal City, Cairo
6     Alam Al- Rum, Marsa Matrouh, Matruh Chalets, M...
15    Taj City Compound, 1st Settlement, New Cairo, ...
27                        Talala, New Heliopolis, Cairo
Name: location, dtype: str
****************************************************************************************************
1     33000000
4      8200000
6     20000000
15    10497000
27     3600000
Name: price, dtype: int64
****************************************************************************************************
1     EGP
4     EGP
6     EGP
15    EGP
27    EGP
Name: currency, dtype: str
****************************************************************************************************
1     4
4     4
6     3
15    3
27    2
Name: bedrooms, dtype: int64
****************************************************************************************************
1     4.0
4     4.0
6     4.0
15    3.0
27    2.0
Name: bathrooms, dtype: float64
****************************************************************************************************
1       Furnished
4     Unfurnished
6     Unfurnished
15    Unfurnished
27    Unfurnished
Name: furnished, dtype: str
****************************************************************************************************
1     Built in Kitchen Appliances, Furnished, Covere...
4     Gym or Health Club, Swimming Pool, Jacuzzi, Sa...
6     Built in Kitchen Appliances, Sea view, Gym or ...
15    Built in Kitchen Appliances, Gym or Health Clu...
27    Built in Kitchen Appliances, Gym or Health Clu...
Name: amenities, dtype: str
****************************************************************************************************
1     331 Sq. M.
4     206 Sq. M.
6     141 Sq. M.
15    155 Sq. M.
27    100 Sq. M.
Name: details, dtype: str
****************************************************************************************************
1      Santi Tareq
4     Dina Mohamed
6     Dina Mohamed
15    Dina Mohamed
27    Dina Mohamed
Name: agent_name, dtype: str
****************************************************************************************************
1     ["https://images.bayut.eg/thumbnails/49130472-...
4     ["https://images.bayut.eg/thumbnails/49126818-...
6     ["https://images.bayut.eg/thumbnails/49126932-...
15    ["https://images.bayut.eg/thumbnails/49128950-...
27    ["https://images.bayut.eg/thumbnails/49126026-...
Name: property_image_urls, dtype: str
****************************************************************************************************
1        Ready
4     Off-Plan
6     Off-Plan
15    Off-Plan
27    Off-Plan
Name: completion_status, dtype: str
****************************************************************************************************
1     Primary
4     Primary
6     Primary
15    Primary
27    Primary
Name: ownership, dtype: str
****************************************************************************************************

In [33]:
df.reset_index(drop=True,inplace=True)
print(df.head())

                                                 url     reference_number  \
0  https://www.bayut.eg/en/property/details-50403...  Bayut - 1412-oZqhry
1  https://www.bayut.eg/en/property/details-50403...  Bayut - 1016-uZZby7
2  https://www.bayut.eg/en/property/details-50403...  Bayut - 1016-kb5nH9
3  https://www.bayut.eg/en/property/details-50403...  Bayut - 1016-Z08cJv
4  https://www.bayut.eg/en/property/details-50403...  Bayut - 1016-4dp8xi

          id   broker_display_name  \
0  504034847  Property Hills One 1
1  504034491    Falcon Real Estate
2  504034500    Falcon Real Estate
3  504034685    Falcon Real Estate
4  504034450    Falcon Real Estate

                                               title property_type  \
0  A villa overlooking a landscaped area, ready f...         Villa
1  Duplex 206m + Garden Open View Opposite Madina...     Apartment
2  1st Row Lagoon Twin Chalet + Garden 60s to Sea...        Chalet
3  Villa view landscape & water feature 50% disco...         Villa
4  Ultra Lux Apartment 33% Off + 10Y Plan Next to...     Apartment

                                         description  \
0  A fully finished villa with an ultra-superb fi...
1  206m² Private Garden Duplex | Prime Madinaty V...
2  Invest with Diar Qatar in Alam Al Roum’s MEGA ...
3  Prime villa available on system in Taj City Co...
4  Apartment with a breathtaking Landscape View i...

                                            location     price currency  \
0                  Sodic East, New Heliopolis, Cairo  33000000      EGP
1                       Sarai, Mostakbal City, Cairo   8200000      EGP
2  Alam Al- Rum, Marsa Matrouh, Matruh Chalets, M...  20000000      EGP
3  Taj City Compound, 1st Settlement, New Cairo, ...  10497000      EGP
4                      Talala, New Heliopolis, Cairo   3600000      EGP

   bedrooms  bathrooms    furnished  \
0         4        4.0    Furnished
1         4        4.0  Unfurnished
2         3        4.0  Unfurnished
3         3        3.0  Unfurnished
4         2        2.0  Unfurnished

                                           amenities     details  \
0  Built in Kitchen Appliances, Furnished, Covere...  331 Sq. M.
1  Gym or Health Club, Swimming Pool, Jacuzzi, Sa...  206 Sq. M.
2  Built in Kitchen Appliances, Sea view, Gym or ...  141 Sq. M.
3  Built in Kitchen Appliances, Gym or Health Clu...  155 Sq. M.
4  Built in Kitchen Appliances, Gym or Health Clu...  100 Sq. M.

     agent_name                                property_image_urls  \
0   Santi Tareq  ["https://images.bayut.eg/thumbnails/49130472-...
1  Dina Mohamed  ["https://images.bayut.eg/thumbnails/49126818-...
2  Dina Mohamed  ["https://images.bayut.eg/thumbnails/49126932-...
3  Dina Mohamed  ["https://images.bayut.eg/thumbnails/49128950-...
4  Dina Mohamed  ["https://images.bayut.eg/thumbnails/49126026-...

  completion_status ownership
0             Ready   Primary
1          Off-Plan   Primary
2          Off-Plan   Primary
3          Off-Plan   Primary
4          Off-Plan   Primary

In [34]:
df.head()

,url,reference_number,id,broker_display_name,title,property_type,description,location,price,currency,bedrooms,bathrooms,furnished,amenities,details,agent_name,property_image_urls,completion_status,ownership
0,https://www.bayut.eg/en/property/details-50403...,Bayut - 1412-oZqhry,504034847,Property Hills One 1,"A villa overlooking a landscaped area, ready f...",Villa,A fully finished villa with an ultra-superb fi...,"Sodic East, New Heliopolis, Cairo",33000000,EGP,4,4.0,Furnished,"Built in Kitchen Appliances, Furnished, Covere...",331 Sq. M.,Santi Tareq,"[""https://images.bayut.eg/thumbnails/49130472-...",Ready,Primary
1,https://www.bayut.eg/en/property/details-50403...,Bayut - 1016-uZZby7,504034491,Falcon Real Estate,Duplex 206m + Garden Open View Opposite Madina...,Apartment,206m² Private Garden Duplex | Prime Madinaty V...,"Sarai, Mostakbal City, Cairo",8200000,EGP,4,4.0,Unfurnished,"Gym or Health Club, Swimming Pool, Jacuzzi, Sa...",206 Sq. M.,Dina Mohamed,"[""https://images.bayut.eg/thumbnails/49126818-...",Off-Plan,Primary
2,https://www.bayut.eg/en/property/details-50403...,Bayut - 1016-kb5nH9,504034500,Falcon Real Estate,1st Row Lagoon Twin Chalet + Garden 60s to Sea...,Chalet,Invest with Diar Qatar in Alam Al Roum’s MEGA ...,"Alam Al- Rum, Marsa Matrouh, Matruh Chalets, M...",20000000,EGP,3,4.0,Unfurnished,"Built in Kitchen Appliances, Sea view, Gym or ...",141 Sq. M.,Dina Mohamed,"[""https://images.bayut.eg/thumbnails/49126932-...",Off-Plan,Primary
3,https://www.bayut.eg/en/property/details-50403...,Bayut - 1016-Z08cJv,504034685,Falcon Real Estate,Villa view landscape & water feature 50% disco...,Villa,Prime villa available on system in Taj City Co...,"Taj City Compound, 1st Settlement, New Cairo, ...",10497000,EGP,3,3.0,Unfurnished,"Built in Kitchen Appliances, Gym or Health Clu...",155 Sq. M.,Dina Mohamed,"[""https://images.bayut.eg/thumbnails/49128950-...",Off-Plan,Primary
4,https://www.bayut.eg/en/property/details-50403...,Bayut - 1016-4dp8xi,504034450,Falcon Real Estate,Ultra Lux Apartment 33% Off + 10Y Plan Next to...,Apartment,Apartment with a breathtaking Landscape View i...,"Talala, New Heliopolis, Cairo",3600000,EGP,2,2.0,Unfurnished,"Built in Kitchen Appliances, Gym or Health Clu...",100 Sq. M.,Dina Mohamed,"[""https://images.bayut.eg/thumbnails/49126026-...",Off-Plan,Primary

In [35]:
df.to_csv("Cleaned_Properties.csv",index=False)